import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"
import Participants from "../components/Participants"
import LastWinner from "../components/LastWinner"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Smart Contract Lottery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <LotteryEntrance />
            <div className="flex flex-row">
                <Participants className="basis-3/4" />
                <LastWinner className="basis-1/4" />
            </div>
        </div>
    )
}
